### ISSUE TITLE
Wrong regex in ieee-mac-splunk.sh

### ISSUE THREAD

**Issue by jebabin** [ffirg/Splunk#1]
Hello,

You have an error in ieee-mac-splunk.sh
`sed -e 's/  /,/' -re 's/([0-9]+)-([0-9]+)-/\1:\2:/' < $tmpb > $ieee`
should be
`sed -e 's/  /,/' -re 's/([0-9A-F]+)-([0-9A-F]+)-/\1:\2:/' < $tmpb > $ieee`

Else you will not replace - by : for mac address containing A,B,C,D,E or F in the first two bytes

**Comment by ffirg** [comment]
Many thanks for debugging! Changed code, closing issue
